name = "tg"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Sans-io package to work with a small part of the Telegram Bot API"
licences = ["Apache-2.0"]
repository = { type = "github", user = "JonasGruenwald", repo = "tg" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
birdie = ">= 1.5.4 and < 2.0.0"
